baseURL = 'https://gliwka.eu/'
languageCode = 'en-us'
title = 'Matthias Gliwka'
theme = 'hugo-neso'
mainSections = ['posts']

[markup.goldmark.renderer]
hardWraps = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 2

[[menu.footer]]
    identifier = "privacy"
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 1
[[menu.footer]]
    identifier = "legal-notice"
    name = "Legal Notice"
    url = "/legal-notice/"
    weight = 2

[params]
    [params.neso]
        time_format                        = "2. January 2006"
        show_breadcrumbs                   = true
        ext_link_indicator                 = true
        ext_link_no_opener_referrer        = true
        ext_link_new_window                = true
        force_color_scheme                 = "dark"
        [params.neso.page]
            enable_comments                = true
        [params.neso.seo]
            site_description                 = ""
            site_keywords                    = []
            site_author                      = "Matthias Gliwka"
        [params.neso.branding]
        logo_text                        = "gliwka.eu"
        hide_logo_text                   = false
        [params.neso.social]
        [[params.neso.social.links]]
            name                           = "Github"
            url                            = "https://github.com/gliwka"
        [[params.neso.social.links]]
            name                           = "LinkedIn"
            url                            = "https://www.linkedin.com/in/gliwka/"
        [[params.neso.social.links]]
            name                           = "Signal"
            url                            = "https://signal.me/#eu/JocUtni5NzWiEGW2iXLE8MW3JvbtfH5wkyZX8tH3J500oDcnoPxDB5f8UlAnch2r"
        [[params.neso.social.links]]
            name                           = "Email"
            url                            = "mailto:blog@gliwka.eu"
        [params.neso.home]
            display_mode                     = "profile"
        [params.neso.home.list]
            featured_entries_limit         = 2
        [params.neso.home.profile]
            avatar_image                   = "img/avatar.jpeg"
            avatar_image_size              = 260
            avatar_image_size_sm           = 260
            avatar_image_alt_text          = "Matthias Gliwka's avatar"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'